version: '3.8'

services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - ..:/workspace:cached
    ports:
      - "8888:8888"
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/workspace
      - MPLBACKEND=module://IPython.backend_inline
      - MPLCONFIGDIR=/home/jupyter/.config/matplotlib
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''